### ISSUE TITLE
Error when trying to start up a stoneblock

### ISSUE THREAD

**Issue by justin9900** [null2264/SkyblockCreator#1]
https://pastebin.com/bBhXDm6w

trying to make a stoneblock server with version 1.3.1 of Skyblock creator, when i run the server it crashes and keeps altering the level type to level-type=skyblockcreator\:stoneblock from level-type=skyblockcreator:stoneblock not sure whats happening

**Comment by null2264** [comment]
Fixed in version [1.3.2](https://modrinth.com/mod/skyblock-creator/version/1.3.2-ALPHA+1.18.2)
