### ISSUE TITLE
name changing

### ISSUE THREAD

**Issue by GlitchFemboyFox** [null2264/SkyblockCreator#8]
i tried to make a custom world it fully works i just cant figure out to make the name normal
![afbeelding_2023-06-18_212548985](https://github.com/null2264/SkyblockCreator/assets/136999370/b7c1c185-c8b5-4ee0-a2f0-43ce632c77e1)
![afbeelding_2023-06-18_212710903](https://github.com/null2264/SkyblockCreator/assets/136999370/50718b3f-9e2c-43d1-9873-aecd456d7bef)
 please tell me how i can fix this

**Comment by null2264** [comment]
You use a resource pack for that (specifically the `lang` folder), you can use KubeJS or [load-my-resources](https://modrinth.com/mod/load-my-resources) mod to make the resource pack automatically load.

**Comment by GlitchFemboyFox** [comment]
how do i add the recourcepack using load my recources idk what files to use

**Comment by null2264** [comment]
You just put the resource pack's `assets` folder into `resources` folder in your `.minecraft` folder (the same folder that has `config` and `mods` folders in it). Here's an example for the lang folder: https://github.com/Laskyyy/Create-Astral/blob/ee611c386992db9b71eb77db9e96c4db4edc2b1c/resourcepacks/Reim%20GUI%20%2B%20Default%20Dark/assets/minecraft/lang/en_us.json

**Comment by null2264** [comment]
So the the folder structure will look like this:

```
.minecraft/
├── config/
│   └── ...
├── mods/
│   └── ...
└── resources/
    └── minecraft/
        └── lang/
            ├── en_us.json
            ├── en_gb.json
            └── ...
```

**Comment by GlitchFemboyFox** [comment]
Where do i find the recourcepack for it? I looked in folder recourcepack but nothing is there

**Comment by null2264** [comment]
Uhh, you just make it manually...

**Comment by GlitchFemboyFox** [comment]
How do i make it

**Comment by null2264** [comment]
- Install load-my-resources mod (obviously)
- Create new folder, name it "resources"
- Create another folder inside "resources", call it "minecraft", then another folder inside "minecraft", "lang"
- Finally create a file depending on the language you want to support in "lang" folder, for this example let's do US English (default Minecraft language), so we create `en_us.json`
- Inside the file write something like this:

```json
{
    "generator.skyblockcreator.creators_island": "Creators Island"
}
```

**Comment by GlitchFemboyFox** [comment]
tried it still doesnt work

**Comment by null2264** [comment]
Strange, maybe try using KubeJS instead? I did mine with KubeJS once https://github.com/null2264/Skyblock/blob/master/kubejs/assets/kubejs/lang/en_us.json

**Comment by GlitchFemboyFox** [comment]
nvm it works it automaticcaly put a capital letter for folders and that made it not work

**Comment by null2264** [comment]
Aight cool, glad that works!
